#+title: Заметки о реализации Истока
#+author: Centrix14
#+startup: overview
* Coeden
/Coeden/ (койден) — легковесная иерархическая СУБД, написана на JavaScript, может работать прямо в браузере. Данные хранит в JSON специальной структуры.

** Основные идеи
Coeden позволяет хранить иерархические структуры данных. Coeden придумана, чтобы решать проблемы Истока — инструмента для создания диаграмм МИСО. В силу этого Coeden имеет несколько отличий от классических И-СУБД:
- узлы могут быть разделяемыми, т. е. принадлежать сразу нескольким родителям;
- узлы могут выводиться: если узел A имеет подузел B, а он — подузел C, то возможно сделать C также подузлом A.

Как и другие И-СУБД Coeden не поддерживает рекурсивные деревья.

** Определения (душнятина всякая)
1. Если узел A содержит узел B (B ∈ A), то A — надузел, B — подузел.
2. Надузел и подузел /родственны/, это родство имеет два параметра: логический и физический. Логический параметр родства описывает, то кому данный узел родственен, когда как физический — где он хранится.
3. Параметры родства могут принимать одно из трёх значений: здесь (=Here=), надузел (=Supnode=), подузел (=Subnode=). Подробнее о смысле этих значений см. [[*Параметры родства]].
4. Узлы могут /соседствовать/. Узлы A и B являются соседями, когда ∃C: A ∈ C ∧ B ∈ C. Так как родство узлов имеет два аспекта (параметра), то и соседство может быть логическим и физическим.
5. Узлы могут содержать ссылки на разделяемые узлы. Если A ∈ B только логически, а физически A ∈ C (B ∈ C), то A — ссылка на разделяемый узёл. Узел B при этом называется /средним/.
6. Узлы могут быть разделяемыми. Если A ∈ B и ∃C: C ∈ B ∧ (C — ссылка на разделяемый узел A), то A — разделяемый узел. Проще говоря, разделяемый узел — это узел, на который в дереве есть разделяемая ссылка.
7. Узлы могут содержать ссылки на выводимые узлы. Если A ∈ B только логически, а физически A ∈ C (C ∈ B), то A — ссылка на выводимый узел. Узел B при этом называется /средним/.
8. Узлы могут содержать выводимые подузлы. Если A ∈ B и ∃C: C ∈ B ∧ (C — ссылка на выводимый узел), то A — выводимый подузел. Проще говоря, выводимый подузел, это узел, на который в дереве есть выводимая ссылка.

** Параметры родства
Как говорилось ранее, один узел может принадлежать другому узлу в двух аспектах:
- логическом,
- физическом.

Взятые как свойства объекта, эти аспекты называются параметрами.

В случае, когда один узел входит в состав другого и только в него, различия между логическим и физическим владением не возникает. Аспекты разделяются тогда, когда необходимо описать разделение и вывод узлов.

При организации разделения и вывода узлов встаёт два взаимосвязанных вопроса: (1) как /связать/ данный узел с другим, (2) где /хранить/ данный узел. Рассмотрение первого вопроса вводит понятие логического владения, а второго — физического.

Обозначим эти два аспекта принадлежности двумя свойствами: =logicalOwn= и =physicalOwn=. Оба этих свойства могут принимать одно из трёх значений: здесь (=Here=), подузел (=Subnode=), надузел (=Supnode=). Значение сочетаний этих значений следующее:
| Значение                   | logicalOwn | physicalOwn |
|----------------------------+------------+-------------|
| собственный узел           | здесь      | здесь       |
| ссылка на разделяемый узел | здесь      | надузел     |
| разделяемый узел           | подузел    | здесь       |
| ссылка на выводимый узел   | здесь      | подузел     |

Случаи, не рассмотренные в таблице, не имеют смысла.

Приведённая таблица не сходится с пунктами выше только в одном пункте: в ней нет случая выводимого узла. Так получается потому, что выводимый узел с точки зрения параметров родства — это собственный узел. Похожее случается с разделяемыми узлами, которые принадлежат своим надузлам. Именно поэтому тип узла определяется не только параметрами хранения, но существованием ссылок.

Свойства =logicalOwn= и =physicalOwn= принадлежат классу =Subnode=. В зависимости от сочетания значений этих свойств, различными будут значения других двух свойств — =id= и =node=. Эти сочетания таковы:
| Сочетание                     | id | node |
|-------------------------------+----+------|
| собственный узел              | +  | +    |
| ссылка на разделяемый узел    | +  | -    |
| разделяемый узел              | +  | +    |
| выводимый узел                | +  | -    |

Символом «+» обозначено наличие значения, а «-» — отсутствие его. Свойство =id= хранит уникальный номер узла, содержащегося в контейнере, а =node= — сам этот узел.

** Классы Node и Subnode
Классы =Node= и =Subnode= формируют основу системы, при помощи них можно описать иерархию /узлов/, рассмотренную ранее.

Элемент иерархии, т. е. узел, описывается классом =Node=. Особенности вхождения одного узла в состав другого описываются классом =Subnode=. Можно сказать, что =Subnode= — это контейнер.

*** Свойства класса =Node=
Прокомментируем следующие свойства класса:
- =id=,
- =subnodes=.

**** =id=
Свойство =id= описывает уникальный номер узла в иерархии. Этот номер неизменен и может быть установлен только при создании узла при помощи одноимённого аргумента конструктора.

**** =subnodes=
Свойство =subnodes= хранит узлы, которые входят в состав данного. =subnodes= — это хэш-таблица, где ключом служит =id= узла, а значением — контейнер, содержащий этот узел.

При хранении, =id= узла повторяется трижды: он входит в объект узла, входит в объект контейнера, является ключом хэш-таблицы. Подобная избыточность введена из соображений удобства. Если потребуется сокращение объёма требуемой памяти, =subnodes= можно превратить в массив.

*** Свойства класса =Subnode=
Свойства =logicalOwn= и =physicalOwn= рассмотрены в разделе [[*Механизм владения]]. Здесь рассматриваются:
- =id=,
- =node=.

**** =id=
Свойство =id= хранит уникальный номер узла, содержащегося в контейнере. Собственных уникальных номеров контейнеры *не* имеют. Необходимость хранения id узла в контейнере продиктована реализацией механизма владения. Контейнеры, содержащие выведенные и общие подузлы должны содержать id, тогда как свойство =node= будет пустым.

**** =node=
Свойство =node= хранит узел, содержащийся в контейнере. У контейнеров, хранящих общие и разделяемые узлы это свойство равно =null=.

*** Связи между узлами
Узлы образуют иерархию, так что все узлы, кроме корневого, входят в какие-то другие и формы этого вхождения образуют различные /связи/ между узлами. Существуют следующие связи:
- соседство: если /a/ и /b/ — узлы, то они соседствуют, если ∃C: a ∈ C ∧ b ∈ C;
- логическое родство: если /a/ ∈ B, то они являются логическими родственниками тогда, когда B владеет /a/ логически;
- физическое родство: определяется так же, как и логическое с той разницей, что владение должно быть физическим;
- 

* COMMENT
** Ошибки проектирования =Result=
Класс =Result= спроектирован, как универсальный: он предназначен для описания как нормальных, так и ошибочных состояний.

Это было неверным проектным решением, которое я перенёс из прежней версии. Следует от общего класса =Result= унаследовать отдельные классы для успеха, ошибки и пустого результата.

Ещё одна важная особенность =Result= это способ передачи значений. Сейчас это выполняется не слишком безопасно, хотя весьма изящно: через добавление полей к объекту. Это не правильно: вместо этого в классе нужно создать хеш-таблицу и методы, проксирующие запись и чтение значений.

*** Различение простых и сложных методов по возвращаемому поведению
Методы /возвращают поведение/ в том смысле, что кроме непосредственных значений они также возвращают пустые и нейтральные результаты, ошибки и т. д.

Если метод возвращает только значения, то он простой. Таковы многие методы, работающие с числами и т. п.

Если метод способен вернуть ошибку или пустой (нейтральный) результат, он относится к сложным и должен возвращать =Result=.
