#+title: Заметки о реализации Истока
#+author: Centrix14
#+startup: overview
* Классы Node и Subnode
Классы =Node= и =Subnode= формируют основу системы, при помощи них можно описать иерархию /узлов/ со следующими свойствами:
- узлы входят друг в друга, вхождение одного узла в состав другого — единственная форма связи;
- узлы могут быть /разделяемыми/, в таком случае узел B может входить в состав любого числа узлов A₁, A₂, …
- узлы могут /выводиться/, в таком случае узел C, принадлежащий B, может принадлежать и A, если B принадлежит A.

Элемент иерархии, т. е. узел, описывается классом =Node=. Особенности вхождения одного узла в состав другого описываются классом =Subnode=. Можно сказать, что =Subnode= — это контейнер. Вхождение узлов друг в друга так же называется /владением/.

** Свойства класса =Node=
Прокомментируем следующие свойства класса:
- =id=,
- =subnodes=.

*** =id=
Свойство =id= описывает уникальный номер узла в иерархии. Этот номер неизменен и может быть установлен только при создании узла при помощи одноимённого аргумента конструктора.

*** =subnodes=
Свойство =subnodes= хранит узлы, которые входят в состав данного. =subnodes= — это хэш-таблица, где ключом служит =id= узла, а значением — контейнер, содержащий этот узел.

При хранении, =id= узла повторяется трижды: он входит в объект узла, входит в объект контейнера, является ключом хэш-таблицы. Подобная избыточность введена из соображений удобства. Если потребуется сокращение объёма требуемой памяти, =subnodes= можно превратить в массив.

** Свойства класса =Subnode=
Свойства =logicalOwn= и =physicalOwn= рассмотрены в разделе [[*Механизм владения]]. Здесь рассматриваются:
- =id=,
- =node=.

*** =id=
Свойство =id= хранит уникальный номер узла, содержащегося в контейнере. Собственных уникальных номеров контейнеры *не* имеют. Необходимость хранения id узла в контейнере продиктована реализацией механизма владения. Контейнеры, содержащие выведенные и общие подузлы должны содержать id, тогда как свойство =node= будет пустым.

*** =node=
Свойство =node= хранит узел, содержащийся в контейнере. У контейнеров, хранящих общие и разделяемые узлы это свойство равно =null=.

** Механизм владения
Один узел может принадлежать другому узлу в двух аспектах:
- логическом,
- физическом.

В случае, когда один узел входит в состав другого и только в него, различия между логическим и физическим владением не возникает. Аспекты разделяются тогда, когда необходимо описать разделение и вывод узлов.

При организации разделения и вывода узлов встаёт два взаимосвязанных вопроса: (1) как /связать/ данный узел с другим, (2) где /хранить/ данный узел. Рассмотрение первого вопроса вводит понятие логического владения, а второго — физического.

Обозначим эти два аспекта принадлежности двумя свойствами: =logicalOwn= и =physicalOwn=. Оба этих свойства могут принимать одно из трёх значений: здесь, подузел, надузел. Значение сочетаний этих значений следующее:
| Значение                | logicalOwn | physicalOwn |
|-------------------------+------------+-------------|
| собственный подузел     | здесь      | здесь       |
| выведенный подузел      | здесь      | подузел     |
| разделяемый подузел (д) | здесь      | надузел     |
| разделяемый подузел (р) | подузел    | здесь       |
| X                       | подузел    | подузел     |
| X                       | подузел    | надузел     |
| X                       | надузел    | здесь       |
| X                       | надузел    | подузел     |
| X                       | надузел    | надузел     |

Случаи, обозначенные «X» не имеют смысла. Прокомментируем случаи разделяемых подузлов.

Общий подузел (д) — случай, когда данный узел владеет иным узлом, общим для данного уровня. В таком случае этот узел лишь логически хранит в себе общий узел, а физически он принадлежит родителю.

Общий подузел (р) — случай, когда данный узел владеет иным узлом лишь физически, логически он является общим для подузлов данного.

Свойства =logicalOwn= и =physicalOwn= принадлежат классу =Subnode=. В зависимости от сочетания значений этих свойств, различными будут значения других двух свойств — =id= и =node=. Эти сочетания таковы:
| Сочетание               | id | node |
|-------------------------+----+------|
| собственный подузел     | +  | +    |
| выведенный подузел      | +  | -    |
| разделяемый подузел (д) | +  | -    |
| разделяемый подузел (р) | +  | +    |

Символом =+= обозначено наличие значения, а =-= — отсутствие его. Свойство =id= хранит уникальный номер узла, содержащегося в контейнере, а =node= — сам этот узел.

** Методы =Node=
Методы, оперирующие узлами, разделяются на две группы:
- местные — оперируют подузлами *только* данного узла,
- глобальные — оперируют *всем деревом*, корнем которого является данный узел.

*** Местные методы
- =subnodes= — возвращает массив подузлов данного узла,
- =getSubnode= — возвращает подузел данного узла, удовлетворяющий условию,
- =hasSubnode= — проверяет, принадлежит ли данному узлу подузел с переданным id,
- =addSubnode= — добавляет к данному узлу подузел,
- =removeSubnode= — удаляет из данного узла подузел с переданным id.
